apiVersion: v1
kind: ConfigMap
metadata:
  name: paintman-config
  namespace: paintman
  labels:
    app: paintman
data:
  SPOOLMAN_DB_TYPE: postgres
  SPOOLMAN_DB_HOST: paintman-db
  SPOOLMAN_DB_PORT: "5432"
  SPOOLMAN_DB_NAME: postgres
  SPOOLMAN_DB_USERNAME: postgres
  SPOOLMAN_METRICS_ENABLED: "false"