apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
    name: homepage
    namespace: homepage
    labels:
        app.kubernetes.io/name: homepage
    annotations:
        kubernetes.io/service-account.name: homepage
sops:
    age:
        - recipient: age1hm46de9enhwh4qlz84s2th5lxpqfwz3sudjc9luk2tpyctaws39qa9r5tg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtSlZ6cnUxMzRUVHdOMjB2
            UXdhYmtSUFFXUEdZVStNS1lsbmhPS3lxcWlRCktKTUFXbDI3eE8zNjFRN0dKWE9a
            Wk5FOTNDT0hzQ1d3bVZvc1ZSeTMyUGsKLS0tIDVwQnI3UytiY2lIRUVlNzVqUlhQ
            SW44cHpvTGc1UHFXY3pqUUdBTDBvNkUKPMvVmEMpCRydpWyo43OB8IQSn+eO/zj6
            DALCW235yzcLU7nK3bm6h3ZpoEOD/n9VhvTKP2Rp7NLEqNYvSGBeeQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-11T09:39:27Z"
    mac: ENC[AES256_GCM,data:+SKLwnMyM8k9JGRP/XfWunWf38mlKT4kGcDjxtTjCvHFBeqg1eZ8gRnQ0jOyX3s0+vhFgC4AGRghFSiZX6ZUo9NO0gdW9RXQcm1FsrgSjht1idLsrqrzj11EcTWeI2qt6tQFJkWjDkHIdwYPqGaGbIPM2sRuQhGmO1vcPVQGE3I=,iv:dRpe+ulDR/wBFBsOEcZ6OYBZdIwfjfJRPygvcFcQQwI=,tag:mUIb6PJEU/Id9TzOJf97xg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: v1
kind: Secret
metadata:
    name: pihole-token
    namespace: homepage
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:IzEU0ya/JWbm8iWUoK0CyTvNng==,iv:da90z6BzAxGrI4jXU7PCoa0U1+rRwLRX8bRyRUcX7H0=,tag:WuP75h6xlGka4H9LhnHkZQ==,type:str]
sops:
    age:
        - recipient: age1hm46de9enhwh4qlz84s2th5lxpqfwz3sudjc9luk2tpyctaws39qa9r5tg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtSlZ6cnUxMzRUVHdOMjB2
            UXdhYmtSUFFXUEdZVStNS1lsbmhPS3lxcWlRCktKTUFXbDI3eE8zNjFRN0dKWE9a
            Wk5FOTNDT0hzQ1d3bVZvc1ZSeTMyUGsKLS0tIDVwQnI3UytiY2lIRUVlNzVqUlhQ
            SW44cHpvTGc1UHFXY3pqUUdBTDBvNkUKPMvVmEMpCRydpWyo43OB8IQSn+eO/zj6
            DALCW235yzcLU7nK3bm6h3ZpoEOD/n9VhvTKP2Rp7NLEqNYvSGBeeQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-11T09:39:27Z"
    mac: ENC[AES256_GCM,data:+SKLwnMyM8k9JGRP/XfWunWf38mlKT4kGcDjxtTjCvHFBeqg1eZ8gRnQ0jOyX3s0+vhFgC4AGRghFSiZX6ZUo9NO0gdW9RXQcm1FsrgSjht1idLsrqrzj11EcTWeI2qt6tQFJkWjDkHIdwYPqGaGbIPM2sRuQhGmO1vcPVQGE3I=,iv:dRpe+ulDR/wBFBsOEcZ6OYBZdIwfjfJRPygvcFcQQwI=,tag:mUIb6PJEU/Id9TzOJf97xg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
