apiVersion: v1
data:
    password: ENC[AES256_GCM,data:eiRTnLfYsVV4tNMT9YtfapnyMsHiFY7+380tWFmyVGI=,iv:a/Dp5LgyIXy1PMxNsZHK9dY3af9NXfY72tXlc7FZv/g=,tag:wFoqTvLC77poVtgPebbLbA==,type:str]
    username_pmp: ENC[AES256_GCM,data:CEghxUbOHlouQCvArdy7ew==,iv:O1x+mUYyD0L+d7i2+Vf6U5sVkxhz5r2Jjci2TawwH4c=,tag:6TBHmtkL76ccTiQY8XM/MA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: protonvpn-credentials
    namespace: media
sops:
    age:
        - recipient: age1hm46de9enhwh4qlz84s2th5lxpqfwz3sudjc9luk2tpyctaws39qa9r5tg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvb25VSWY2OFIvaTVna3Vy
            ZUpKcU9MOWJRZDlyeUhJVnU3K1BubVhkSUJrCkpTdmlFVklYZkx0d3VKZ0pCWEwz
            SjMrUU5IZ0o1OTBudmFVcll2QlFxSjQKLS0tIDI0VEZvQ1IzSXdCcXRQSnpYZ1pr
            T3RHaS82d1hBdzFUTG04RndWcGl0Nk0KX1kZB0hw42r1JCdmlnBPvgwTCmYcL8Vv
            WuKAwwzCP7Rj/OIzPnNhNeBORmS2rP9lioNfTJst9gIN50xOmg1AXg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-07T11:32:16Z"
    mac: ENC[AES256_GCM,data:bqUFqcU/vitgBzxIWd0oG2oX76+w97OSl+sIPtpd1ih+PVPxosKg5cpgLx7uyuFpTXTi+6sNd8EH0SRpQo6rmmiL3NbjVS3aEK3how7PUemmlf0szFEhedXAtM5unvnWNs01u5mGvLXxQEplymFNgK/iIpp0wN5imhqKfIWwzpE=,iv:eKB5BDXO9UU59Wa6d/ZmY00SPeSAfTjlr2LNdfVJOjk=,tag:a5ov2zufOb/yXZ2axicjwA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
