apiVersion: v1
data:
    privatekey: ENC[AES256_GCM,data:KP8AAYxBqB/KJVE0CPS6vIVl1S3KS1F6UiZS6Hv0nV34TJZ+CEzJ9+wtGeI=,iv:MxMePZDcwg74T5wA1cKSGZIdyWhtCcNhM/jJT0gE9n4=,tag:QCe20QQz2se2YhNnfzCfGQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: protonvpn-wg
    namespace: media
sops:
    age:
        - recipient: age1hm46de9enhwh4qlz84s2th5lxpqfwz3sudjc9luk2tpyctaws39qa9r5tg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBod2cwRkR1WUVnQy9xWDBY
            L1BFVVZiSndpdVVUQ1BvS3lPdzJiV2xnOFJNCm1UM2xpZmdlTkhPNmZtUHArWDhm
            Y2toU2pEN3hXN0hmTHlSNWlsc2s2cjAKLS0tIDRFT3hsM0VxWDIxTXRPWVROV3hp
            dFlpcFZON05rTW9GTE9yWjB3Wnh4U2cKoPsVREQQ+xxS6oc95hzIc/74ewfAafyP
            hWh1sMvEBsRG0srhSuQe6VonLFvOtuaLiLS6rnnSmmsFeLS5jj6n0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-07T12:24:52Z"
    mac: ENC[AES256_GCM,data:hu2Hdm33erwDKxLhURdcyMJ/6reDODjPejDCY8F6bCbdS0VUBm61w2p/93cR6sa5Miwn9WP/BFpFLiRV+Xc+v8HtuUUIDEdrbnsIMqplwFpt4/O/9J3N1nePq+it79A46QqUhQLC/xkPpzTj7dCZzvZwKPKYlQSTMZRVmt+MWIU=,iv:fmzddVSPwyuQjfBRyasyiujvdEJ5EySrX7E3DZ17GHw=,tag:vd7YkfbmvP5j5U6gNBAM+Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
