apiVersion: v1
stringData:
    privatekey: ENC[AES256_GCM,data:DA2T6FnUMTJqSRu46v8PU8TK74tLuuqFNDcEWjji8D8qHcW+VmhN3wA3c3o=,iv:of9Ovco2VURP5VvhJ+IbZ6aDgRL6jqzogzCm5tIJXkw=,tag:TYjZiRKl6drvbla4q3g0rQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: protonvpn-wg
    namespace: media
sops:
    age:
        - recipient: age1hm46de9enhwh4qlz84s2th5lxpqfwz3sudjc9luk2tpyctaws39qa9r5tg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1Vm9Kdm91Y21tWUEvT0xC
            dHFDL2w5RTI2UkUwM1ZsZXZNRE1ka2ZSZmljCjlrRFNTcWsyNHB5Y0FPdGw1RHdC
            ano4c2kxaTBULzF4NXN1cXNubjRQWkEKLS0tIHU4WHpFb2tkcmRPRGR4d25KbEk5
            S05pV3h1Y1FwQndLcXpVSGlZUDVGclUK1N9CW7C80dXlOsCBdAt5r+4mft0B6jdN
            BUyJFGpyQrASdK54KutGbAuSuwq+4klNsAPwxhd/EvYW8hrXh3GleQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-07T12:38:55Z"
    mac: ENC[AES256_GCM,data:sElsTkeWQX1ht2encOkeF27GPVT8ZicFldo6wCJhKa42CEG6i7YEOc6RvdJ8ZIg3F8iMDeqC6BdROWkklUkpvFGcMrveSkbSR4tJBCn0aS8hmaHTEM2AlLZonQY8NmN6eQd01S7Wv13Ka2DMzJJLHkRYpFAcA36YG9UnI+1tyH4=,iv:TeILe+/vnTxsop71U0MPWHsJXhNiPSxNtVkQfu2Heic=,tag:rSoo6a8Yom4b7+/AMZ1qKg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
