apiVersion: v1
data:
    privatekey: ENC[AES256_GCM,data:9l+e9L4osaTHtiBa6FFEtxMYO0tHZ1C09FYucUUfEQKAt126Dpsne2JEC9pD4SxA15huDTQc/aZLr7O8,iv:Chkxe4S3Ldbcv6tR9q+hnDQMBrYjq1NYwvbTK5gfrLA=,tag:PeJLrSR05Gn6LRky7o8Lyg==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: protonvpn-wg
    namespace: media
sops:
    age:
        - recipient: age1hm46de9enhwh4qlz84s2th5lxpqfwz3sudjc9luk2tpyctaws39qa9r5tg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByZXJFV2x3QXpiNkprQjN1
            a2hyUWYycS91KzZtb3NEQ1V3VWZacnZjRVhVCngvay9NZC9MaEVVbHA3SzFFWGtJ
            VnAxZm03b25xOFhoQVJjb1RUVmNRc1UKLS0tIEFab3haSU9qTlRLR2M0ZE5rRWNY
            U0FRRW0xYUd0Y0VtTXQ1dlN3ck5qOGsKPnvjpW17STZN6o24HRxZ+Uuui/IQgsJa
            lKK6JrQlsRuae/t/mwg+eNjVYXPPE9abH9AY7En9DRo3I3qFdpZWbw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-07T11:32:12Z"
    mac: ENC[AES256_GCM,data:V2s9IrI2wgRIDg01B9uU2YIz+/mS81SfHZ9FZO8rfnxYcV1HI2dQk/gUlqBklH7lzoUs27lBoY9DUNSXGaV/sE++4To16V1qBPn1chPM09oeyflHakPBg8XKf6ex/Jn+rGWAeqlFCYBoxIwTOEncDThUl2fxyIH2Istis7+Dmgw=,iv:Y+6GjeVujc34bv7qCxxWH1RVxU9SNWjAWmyGpeuimNU=,tag:JgDQJSwyoR7nbe0QYQyPBQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
