apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: prometheus
spec:
  selector:
    app: prometheus-server
  ports:
  - protocol: TCP
    port: 8082
    targetPort: 9090
  type: LoadBalancer
