apiVersion: v1
kind: Service
metadata:
  name: spoolman-service
spec:
  selector:
    app.kubernetes.io/name: spoolman
  ports:
    - protocol: TCP
      port: 7912
      targetPort: spoolman-container-port