apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-system
  namespace: flux-system
spec:
  interval: 1m
  targetNamespace: kube-system
  path: ./kubernetes/clusters/my-cluster/kube-system
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system