apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
- ../kubernetes-native/spoolman/spoolman-kustomization.yaml
- ../kubernetes-native/ingress-nginx/nginx-kustomization.yaml