apiVersion: v1
kind: Secret
metadata:
    name: abiotic-factor-oci-secret
    namespace: abiotic-factor
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:7MFleZ+UN3HZa2mSAnwKPRfQMg3hGLAuUikeu156OSMIGZ0aQpJUT9UU1bhMQNwgPOyi9miJHiXoVRXRBGLJDWSqIqIcAGHvKNs3kXgAGa3lWHn/xgkge4iUoJ5C4MuHl3HuqZ3MAuZVvcEJTkYEv++RQ45/HV09+bHZyR1mHrXB6AzvAKxS3VvJ,iv:momPPI1vTbyWuxKX4+zow375Se2tEsiEkKY19sjwnj0=,tag:8BopAvM8giMP1dmVg9CJmA==,type:str]
sops:
    age:
        - recipient: age1hm46de9enhwh4qlz84s2th5lxpqfwz3sudjc9luk2tpyctaws39qa9r5tg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSOCt0ck4yZDBvcFVCRFBl
            c2tiZjhMd3cxTzJpSy9hdEs5WTdDL0piTnk4CnFtTFIwbTg2TE9HN0pibzZtUGJl
            em5VaHp0Q0tWcW9yaThueTZjVWdyZ3cKLS0tIGNkOE1sb21MQ052eEJibXcrNkVm
            aFlFZU5BRDYrR3NMMG84NUJQNURXMmcKHSGe6OBGNWvfNTAxShS262AxzGrrKStB
            VtSJIDuzXMXAusVl/IrkVR65hYbHOiCTePqTcidoyUXiLKjHXSSpMQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-08T08:00:45Z"
    mac: ENC[AES256_GCM,data:cijHpd99qgMHe+EnZ6igzI8o92pf7/qAQsL7mbodmMJ8wMIxpGfUOwrHWDSQbvzIDiz1B7mDa4jjAHpKNcpxXV6TDGxmm34MEWwdOBX21nJy1FnvIQ3wH4PUcKVivl5BmcT4d/8xdQg9dU0D23rUZUBCHWfRr7EPXq9+uB+HH3c=,iv:Pky0TJjhaorBGnsuKRxEeq2ycVy2Yf+mxwG23lLLNx8=,tag:2bJTQ7riuz+uq/qVDnpNfg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
