apiVersion: v1
kind: Secret
metadata:
    name: abiotic-factor-oci-secret
    namespace: abiotic-factor
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:jbaN99ShFzlwgBkM7B9CpTlIPbRDsT206y6P1rKkvKFuxzASdukAykGikd+ez7bnwQ3UO/6OQvXh46sipPjvj3EkHcm7Vea2hnGxXMkSA1fGfiV19O+j7LQDpvq6pqXqDUp9M2L1j8Y3c0RN1KJFkTXOZOarFmuT2mzhG0Fk/Io6PKURrlBk2g==,iv:w1q2dKaWYDU3GCh9m6ZDJu/GOwcY27ZgQkS5oXq/YkE=,tag:8JkwJjfJdWCL7gZ/BCl9Iw==,type:str]
sops:
    age:
        - recipient: age1hm46de9enhwh4qlz84s2th5lxpqfwz3sudjc9luk2tpyctaws39qa9r5tg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOQlA1L2taTElzQUpSRGtn
            L1plMC92MkptYXI4RCtqMVVBYnFFTkFPWXlBCm1GdHlZUjVBUGZxb0ZJcFRWZjEv
            N2dFVTNZVHJRTW1KUVh0QUpQRzZzMzAKLS0tIEpVc29ScTB6eGtPcUJkaEZ2WjR6
            ZWJjY0hydVBpYnphYTUxZ1kwNFM1b1EK6ZnO//0nbpZEn7MQ1F23cDuB4a1Irosc
            gG//8/w8V9WkGB9ujWuAsiIdVVA0JotQ3o06Dc3e+6bCQ3vpFn8vhg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-08T08:08:43Z"
    mac: ENC[AES256_GCM,data:UQPydu8LhYASatLQ9Iurkjc7XWxQ/uWla7jp2yRcXQd6gSl0uYRQD6ceCivDY4I0W4rFg82wafoUbjRX2t/OgpfN5aUC+7i8GVv6mWZMNU0kkYN0bAITyRzGqYTdy2S6RbSJOkRY33UJvd30fdcQbfAc6u5qgP8KNdtmwZlrQ/U=,iv:VFtzkRXFLS1HuclMcDX3Iy76rpOPEsZfd9nHZivhrKI=,tag:oonVqvXNG5PkZm3gENuE9A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
