apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: abiotic-factor
  namespace: abiotic-factor
spec:
  interval: 1h
  url: oci://ghcr.io/kiansajjadi/charts/abiotic-factor
  ref:
    tag: 0.1.0
  secretRef:
    name: abiotic-factor-oci-secret