apiVersion: v1
kind: Secret
metadata:
    name: abiotic-factor-oci-secret
    namespace: abiotic-factor
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:/lC5bfo4NDqK3fM=,iv:2PQ5yx9V8dGaCp87oO8sxuugHHumk0tjubobLlkS+LE=,tag:ePTDKhZn9DuOXk9AJ0h+lg==,type:str]
    password: ENC[AES256_GCM,data:UbRYFnpEiMwxNCJYvpOJDyKpsjKe8U7qJL03OITcFp5vfbSSZ29veQ==,iv:Q8w1YuQ8WR82/aRg2HU5kOespQyRpZbVLVkUtNJRxXU=,tag:ZZSu/j3jldHReIALspdssw==,type:str]
sops:
    age:
        - recipient: age1hm46de9enhwh4qlz84s2th5lxpqfwz3sudjc9luk2tpyctaws39qa9r5tg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqRmdsVVdLQWprcjE1ZUpj
            MGNvUDRKa0xndmwzS1haazNYckEzdWVmWmgwCkozUGFsSTRhcnEycG9HbnpOcWZR
            UG9QZDd2WVV3bnlmMWQzMzMzMVJTZ3MKLS0tIFRCWlZsbWU4L0U3NkdQODR2aDVz
            UzlqVWhGOVVkc2hINk1mc3lVUUJaSEUKymcGCFKeR/DEIXIzrkStVZeJGN96XMf4
            fIQZIjQVYfjSknn4m54b1H0M3XeNtRBMWWC6tODKnmOaGf/LqpoM0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-08T08:21:37Z"
    mac: ENC[AES256_GCM,data:6SihGdam2XribYXdbYQ8sSYkz9lbYwdf5RAjMRtZ8Zdm5CA+T0gcUtfyJgYcXrIAqWYPR7BBCGu3xI0QJLgU2gXNvMO/anLp20SVyhWOfHQwNEJBERmvE0TIwj0mL1Be8oUChGEsooRbvgfJ5dNKNv52n6ZSla0wesSpI2wqfSk=,iv:iDVSPvN1ocwXHChFgpj5wX6Aq0ozDMI/7wufIm8b2Ww=,tag:yhltwXkx2n6kazMS+thidg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
