apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
    namespace: paintman
type: Opaque
stringData:
    github_token: ENC[AES256_GCM,data:9ZmCbZRnttaSsNanlGjba1dGBulW53vKUxi3l7ltKRWu8v16fcQNcQ==,iv:P8nXdXZTmD8RzD8WZeayMGJHDVcX/EeEsyUOxUnbjmE=,tag:lIsOUuxw62trFOvK7tUc4w==,type:str]
sops:
    age:
        - recipient: age1hm46de9enhwh4qlz84s2th5lxpqfwz3sudjc9luk2tpyctaws39qa9r5tg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjbDhpOElnNnAvd2lReVo1
            L3ZvQVJiTUExVU5XZjBaQktpZDFWQW05YkVFCmNhc285TFJ6T0xRSDU5L3Q5cVVn
            aGZXaHYvWThCem1OTFkxQ1BDZm5wZ1EKLS0tIHJiV3I3clVtTHk0NlcrRmhJNUph
            d1pSM1hERk1GMG9YSStwbWg1VHI5NmsKaMJjaen6NkslL7VXOtZYeEs39DRG1tbm
            AA6sZ0fGlOEWFFNSftVmeKBDiWbB4D2L5wtELuMxRcjjOt4q1hdFlw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-08T06:58:15Z"
    mac: ENC[AES256_GCM,data:9WJtDzYFgF30cQa7CKWTCL/+jGN1X0JR0KrqSYt5qsTuSy1MHuEqfv0sqeKoVtGq8uvPdPM55450NR3pbPWetuk+sQdLiecgpn/Gn5Tm1b8SQNWr6W2B4NWGVpN4UfIRb3k3Cly/ILPdhiMgbx54Fqjdsop3SUdZ9pg8vnFFoc4=,iv:vEYyl56tUa624aiX7AIpGHgN5OBX8Ngs3uAdRArzXO0=,tag:M5E2oi6v9DglXsjXkfnVeA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
