apiVersion: v1
kind: Secret
metadata:
    name: abiotic-factor-server-secret
    namespace: abiotic-factor
type: Opaque
stringData:
    server-password: ENC[AES256_GCM,data:G9f97Fk+ZtMQKzVc3eZj9yHFHK4=,iv:SZKWNZwzlPOoHBEwFjO3w/AgzmHyNi+4whfFvUh5+gM=,tag:Y4OixHHGGB6ceJjCUG1tkw==,type:str]
sops:
    age:
        - recipient: age1hm46de9enhwh4qlz84s2th5lxpqfwz3sudjc9luk2tpyctaws39qa9r5tg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOa3EvNmE3OENXVEE0cmU3
            N0t1ZFE1bXdOY1IvQ3VnVlkwMm9BOGNsZEhRCjBISnNOQlZCcFBsMTBLbmpKTzdR
            bXJYTDRtd1ZYcFFnN25hcmRlUWk4anMKLS0tIE5PdlJvUGxsTkRrKzZLTHhZM2Fh
            TUdGSS9zV2QwSERNdWNWRmdvaXJTSTAKYv8lYkmoZOfshbCWeXu72/jBoSqfbmwG
            o8TVrop3BJMTypat5SVLp2IQM26cNZkbaS68+7KxrRxpCeqGR/l1dQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-08T08:02:09Z"
    mac: ENC[AES256_GCM,data:OkgvzvhNKj3sQskJWkPXyjT6RDN43MLGkjtF0WH/h/STYKvV83WoZinPJD0+aZjSghjf/SWKcGcs06xKVywQro77LdS+zSn5ma0G9PTxye4p1Z7gbGBAW5ceXhLYNjaJtd/qGiWv0WvK50XORHjFFpsSSImhdq2Np9HUBkhkS3w=,iv:gVQhlqIaiCGdBeHfjrWcMIlh85FG0U8Mjq1N9ihuF1Q=,tag:usNxicfJ9wiBJbRmvgVWXA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
