# # K3S comes with rancher's local path provisioner allowing us to create pvc claims out of the box using local storage on the respective node
# kind: PersistentVolume
# metadata:
#   name: postgres-pv
#   labels:
#     type: local
#     app: postgres
# spec:
#   storageClassName: manual
#   capacity:
#     storage: "1Gi"
#   volumeMode: Filesystem
#   accessModes:
#     - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Retain
#   hostPath:
#     path: "/mnt/data"
