apiVersion: apps/v1
kind: Deployment
metadata:
  name: spoolman-deployment
  namespace: spoolman
  labels:
    app: spoolman
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spoolman
  template:
    metadata:
      labels:
        app: spoolman
    spec:
      containers:
      - name: spoolman
        image: ghcr.io/donkie/spoolman:latest
        resources:
          requests:
            memory: "200Mi"
            cpu: "50m"
          limits:
            memory: "500Mi"
            cpu: "250m"
        envFrom:
          - configMapRef:
              name: spoolman-config
        env:
          - name: SPOOLMAN_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: POSTGRES_PASSWORD
        ports:
        - containerPort: 8000
          name: spoolman-cport
        livenessProbe:
          httpGet:
            path: /health
            port: 7912
          initialDelaySeconds: 10
          periodSeconds: 3

