apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: spoolman-db
  namespace: spoolman
spec:
  selector:
    matchLabels:
      app: spoolman
  serviceName: spoolman-db
  replicas: 1
  template:
    metadata:
      labels:
        app: spoolman-db
    spec:
      containers:
      - name: spoolman-db
        image: postgres:14.18
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 5432
          name: postgresdb-port
        envFrom:
          - configMapRef:
              name: postgres-config
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: POSTGRES_PASSWORD
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-data
        perstistentVolumeClaim:
          claimName: postgres-pvc