# K3S comes with rancher's local path provisioner allowing us to create pvc claims out of the box using local storage on the respective node - use this in near future
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: spoolman
  labels:
    type: local
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: "1Gi"
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: "/mnt/data"
