apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: spoolman
  namespace: flux-system
spec:
  interval: 1m
  targetNamespace: spoolman
  path: ./kubernetes/clusters/my-cluster/kubernetes-native/spoolman
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system