networkPolicy:
  enabled: true

replicaCount: 1

image:
  repository: ghcr.io/kiansajjadi/abiotic-factor
  tag: latest
  pullPolicy: IfNotPresent

service:
  game:
    port: 7777
  query:
    port: 27015

automountServiceAccountToken: false
securityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
  seccompProfile:
    type: RuntimeDefault

imageSecurityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false  # Game servers typically need write access
  runAsNonRoot: true
  runAsUser: 1000

resources:
  limits:
    cpu: "4"
    memory: 8Gi
  requests:
    cpu: "2"
    memory: 4Gi

preferredNode: homelab-node-0

imagePullSecret: ""

env: []