apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "abiotic-factor.fullname" . }}
  labels:
    {{- include "abiotic-factor.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      {{- if .Values.imagePullSecret }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret }}
      {{- end }}
      automountServiceAccountToken: {{ .Values.automountServiceAccountToken }}
      securityContext:
        runAsNonRoot: {{ .Values.securityContext.runAsNonRoot }}
        runAsUser: {{ .Values.securityContext.runAsUser }}
        runAsGroup: {{ .Values.securityContext.runAsGroup }}
        fsGroup: {{ .Values.securityContext.fsGroup }}
        seccompProfile:
          type: {{ .Values.securityContext.seccompProfile.type }}
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - key: kubernetes.io/hostname
                operator: In
                values:
                  - {{ .Values.preferredNode }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: game
              containerPort: {{ .Values.service.game.port }}
              protocol: UDP
            - name: query
              containerPort: {{ .Values.service.query.port }}
              protocol: UDP
          securityContext:
            allowPrivilegeEscalation: {{ .Values.imageSecurityContext.allowPrivilegeEscalation }}
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: {{ .Values.imageSecurityContext.readOnlyRootFilesystem }}
            runAsNonRoot: {{ .Values.imageSecurityContext.runAsNonRoot }}
            runAsUser: {{ .Values.imageSecurityContext.runAsUser }}
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
          volumeMounts:
            - name: game-data
              mountPath: /server-data
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: game-data
          persistentVolumeClaim:
            claimName: {{ include "abiotic-factor.fullname" . }}-pvc
        - name: tmp
          emptyDir: {}