apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "abiotic-factor.fullname" . }}-pvc
  namespace: {{ .Chart.Name }}
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
