apiVersion: v1
kind: Service
metadata:
  name: {{ include "abiotic-factor.fullname" . }}
  namespace: {{ include "abiotic-factor.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  externalTrafficPolicy: Local
  ports:
    - name: game
      port: {{ .Values.service.game.port }}
      targetPort: {{ .Values.service.game.port }}
      protocol: UDP
    - name: query
      port: {{ .Values.service.query.port }}
      targetPort: {{ .Values.service.query.port }}
      protocol: UDP
  selector:
    app: abiotic-factor
