apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'spoolman'
        static_configs:
          - targets: ['spoolman-service.spoolman.svc.cluster.local:7912']

      - job_name: 'grafana'
        static_configs:
          - targets: ['grafana-service.monitoring.svc.cluster.local:3001']

      - job_name: "nodes"
        static_configs:
          - targets: ['192.168.0.251:9100', '192.168.0.64:9100', '192.168.0.3:9100']

      - job_name: "pods"
        metrics_path: "/metrics/cadvisor"
        scheme: https
        tls_config:
          insecure_skip_verify: true
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        honor_timestamps: true
        kubernetes_sd_configs:
        - role: node

        relabel_configs:
        - action: replace
          source_labels: [__address__]
          regex: '(.*):.*'
          replacement: '${1}:10250'
          target_label: __address__